services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - app_logs:/app/logs
      - app_uploads:/app/uploads
      - app_temp:/app/temp
    environment:
      - FLASK_APP=run.py
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - transferwizard-network
    command: gunicorn --bind 0.0.0.0:5000 run:app

  worker:
    build: .
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - web
    networks:
      - transferwizard-network
    command: celery -A app.celery_app.celery_app worker --loglevel=info

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - transferwizard-network

volumes:
  redis_data:
    driver: local
  app_logs:
    driver: local
  app_uploads:
    driver: local
  app_temp:
    driver: local

networks:
  transferwizard-network:
    driver: bridge
